"""add_phase5_care_tables

Revision ID: 25b5f5fa18e7
Revises: f6cbce1a4f57
Create Date: 2026-06-09 02:07:14.321167
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b5f5fa18e7'
down_revision = 'f6cbce1a4f57'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_handoffs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('staff_id', sa.String(), nullable=False),
    sa.Column('shift_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shift_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dogs_on_site_snapshot', sa.JSON(), nullable=True),
    sa.Column('outstanding_care', sa.JSON(), nullable=True),
    sa.Column('active_medications', sa.JSON(), nullable=True),
    sa.Column('active_alerts', sa.JSON(), nullable=True),
    sa.Column('open_incidents', sa.JSON(), nullable=True),
    sa.Column('staff_notes', sa.Text(), nullable=True),
    sa.Column('follow_up_items', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_handoffs_organization_id'), 'shift_handoffs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_shift_handoffs_staff_id'), 'shift_handoffs', ['staff_id'], unique=False)
    op.create_table('feeding_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('dog_id', sa.String(), nullable=False),
    sa.Column('food_name', sa.String(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('scheduled_times', sa.JSON(), nullable=True),
    sa.Column('preparation_instructions', sa.Text(), nullable=True),
    sa.Column('supplements', sa.Text(), nullable=True),
    sa.Column('food_supplied_by_owner', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feeding_plans_dog_id'), 'feeding_plans', ['dog_id'], unique=False)
    op.create_index(op.f('ix_feeding_plans_organization_id'), 'feeding_plans', ['organization_id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('dog_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dose', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('scheduled_times', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('as_needed', sa.Boolean(), nullable=True),
    sa.Column('storage_instructions', sa.Text(), nullable=True),
    sa.Column('administration_instructions', sa.Text(), nullable=True),
    sa.Column('prescriber', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_dog_id'), 'medications', ['dog_id'], unique=False)
    op.create_index(op.f('ix_medications_organization_id'), 'medications', ['organization_id'], unique=False)
    op.create_table('feeding_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('stay_id', sa.String(), nullable=False),
    sa.Column('dog_id', sa.String(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.String(), nullable=True),
    sa.Column('amount_offered', sa.String(), nullable=True),
    sa.Column('amount_eaten', sa.String(), nullable=True),
    sa.Column('appetite_rating', sa.Enum('EXCELLENT', 'GOOD', 'FAIR', 'POOR', 'REFUSED', name='appetiterating'), nullable=True),
    sa.Column('refusal_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['stays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feeding_events_dog_id'), 'feeding_events', ['dog_id'], unique=False)
    op.create_index(op.f('ix_feeding_events_organization_id'), 'feeding_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_feeding_events_stay_id'), 'feeding_events', ['stay_id'], unique=False)
    op.create_table('medication_administrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('stay_id', sa.String(), nullable=False),
    sa.Column('dog_id', sa.String(), nullable=False),
    sa.Column('medication_id', sa.String(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('administered_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('administered_by', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DUE', 'ADMINISTERED', 'REFUSED', 'MISSED', 'HELD', 'NOT_APPLICABLE', name='medicationstatus'), nullable=False),
    sa.Column('dose_administered', sa.String(), nullable=True),
    sa.Column('exception_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['administered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['stays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_administrations_dog_id'), 'medication_administrations', ['dog_id'], unique=False)
    op.create_index(op.f('ix_medication_administrations_medication_id'), 'medication_administrations', ['medication_id'], unique=False)
    op.create_index(op.f('ix_medication_administrations_organization_id'), 'medication_administrations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_medication_administrations_stay_id'), 'medication_administrations', ['stay_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_administrations_stay_id'), table_name='medication_administrations')
    op.drop_index(op.f('ix_medication_administrations_organization_id'), table_name='medication_administrations')
    op.drop_index(op.f('ix_medication_administrations_medication_id'), table_name='medication_administrations')
    op.drop_index(op.f('ix_medication_administrations_dog_id'), table_name='medication_administrations')
    op.drop_table('medication_administrations')
    op.drop_index(op.f('ix_feeding_events_stay_id'), table_name='feeding_events')
    op.drop_index(op.f('ix_feeding_events_organization_id'), table_name='feeding_events')
    op.drop_index(op.f('ix_feeding_events_dog_id'), table_name='feeding_events')
    op.drop_table('feeding_events')
    op.drop_index(op.f('ix_medications_organization_id'), table_name='medications')
    op.drop_index(op.f('ix_medications_dog_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_feeding_plans_organization_id'), table_name='feeding_plans')
    op.drop_index(op.f('ix_feeding_plans_dog_id'), table_name='feeding_plans')
    op.drop_table('feeding_plans')
    op.drop_index(op.f('ix_shift_handoffs_staff_id'), table_name='shift_handoffs')
    op.drop_index(op.f('ix_shift_handoffs_organization_id'), table_name='shift_handoffs')
    op.drop_table('shift_handoffs')
    # ### end Alembic commands ###
