"""add_phase3_room_service_booking_tables

Revision ID: 78a60d2bbbe5
Revises: a141ced0c87a
Create Date: 2026-06-08 12:00:01.302689
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a60d2bbbe5'
down_revision = 'a141ced0c87a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('room_type', sa.String(), nullable=True),
    sa.Column('max_dogs', sa.Integer(), nullable=True),
    sa.Column('adjacency_group', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_out_of_service', sa.Boolean(), nullable=True),
    sa.Column('out_of_service_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_organization_id'), 'rooms', ['organization_id'], unique=False)
    op.create_table('service_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_overnight', sa.Boolean(), nullable=True),
    sa.Column('display_color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_types_organization_id'), 'service_types', ['organization_id'], unique=False)
    op.create_table('booking_dogs_v2',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('booking_id', sa.String(), nullable=False),
    sa.Column('dog_id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=True),
    sa.Column('arrival_status', sa.Enum('EXPECTED', 'ARRIVED', 'NO_SHOW', 'CANCELLED', name='arrivalstatus'), nullable=True),
    sa.Column('departure_status', sa.Enum('EXPECTED', 'DEPARTED', 'EXTENDED', name='departurestatus'), nullable=True),
    sa.Column('care_notes', sa.Text(), nullable=True),
    sa.Column('eligibility_override', sa.Boolean(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_dogs_v2_booking_id'), 'booking_dogs_v2', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_dogs_v2_dog_id'), 'booking_dogs_v2', ['dog_id'], unique=False)
    op.create_index(op.f('ix_booking_dogs_v2_organization_id'), 'booking_dogs_v2', ['organization_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_dogs_v2_organization_id'), table_name='booking_dogs_v2')
    op.drop_index(op.f('ix_booking_dogs_v2_dog_id'), table_name='booking_dogs_v2')
    op.drop_index(op.f('ix_booking_dogs_v2_booking_id'), table_name='booking_dogs_v2')
    op.drop_table('booking_dogs_v2')
    op.drop_index(op.f('ix_service_types_organization_id'), table_name='service_types')
    op.drop_table('service_types')
    op.drop_index(op.f('ix_rooms_organization_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
