"""add_phase2_customer_dog_tables

Revision ID: 965814446b33
Revises: ffd49af18b69
Create Date: 2026-06-08 02:46:35.820578
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965814446b33'
down_revision = 'ffd49af18b69'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veterinarians',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('clinic_name', sa.String(), nullable=False),
    sa.Column('veterinarian_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_instructions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veterinarians_organization_id'), 'veterinarians', ['organization_id'], unique=False)
    op.create_table('households',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='householdstatus'), nullable=True),
    sa.Column('preferred_contact_method', sa.String(), nullable=True),
    sa.Column('general_notes', sa.Text(), nullable=True),
    sa.Column('referral_source', sa.String(), nullable=True),
    sa.Column('meet_and_greet_status', sa.Enum('REQUIRED', 'SCHEDULED', 'COMPLETED', 'WAIVED', name='meetandgreetstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_households_organization_id'), 'households', ['organization_id'], unique=False)
    op.create_table('behavior_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('dog_id', sa.String(), nullable=False),
    sa.Column('handling_restrictions', sa.Text(), nullable=True),
    sa.Column('known_triggers', sa.Text(), nullable=True),
    sa.Column('dog_compatibility', sa.String(), nullable=True),
    sa.Column('human_compatibility', sa.String(), nullable=True),
    sa.Column('food_guarding', sa.Boolean(), nullable=True),
    sa.Column('toy_guarding', sa.Boolean(), nullable=True),
    sa.Column('barrier_reactivity', sa.Boolean(), nullable=True),
    sa.Column('leash_behavior', sa.Text(), nullable=True),
    sa.Column('escape_behavior', sa.Text(), nullable=True),
    sa.Column('bite_history', sa.Boolean(), nullable=True),
    sa.Column('bite_history_detail', sa.Text(), nullable=True),
    sa.Column('muzzle_required', sa.Boolean(), nullable=True),
    sa.Column('handlers_required', sa.Integer(), nullable=True),
    sa.Column('approved_playgroups', sa.Text(), nullable=True),
    sa.Column('prohibited_pairings', sa.JSON(), nullable=True),
    sa.Column('active_safety_alert', sa.Boolean(), nullable=True),
    sa.Column('safety_alert_detail', sa.Text(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_profiles_dog_id'), 'behavior_profiles', ['dog_id'], unique=True)
    op.create_index(op.f('ix_behavior_profiles_organization_id'), 'behavior_profiles', ['organization_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('household_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('contact_type', sa.Enum('PRIMARY', 'SECONDARY', 'EMERGENCY', 'AUTHORIZED_PICKUP', 'OTHER', name='contacttype'), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_emergency_contact', sa.Boolean(), nullable=True),
    sa.Column('is_authorized_pickup', sa.Boolean(), nullable=True),
    sa.Column('relationship_to_household', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_household_id'), 'contacts', ['household_id'], unique=False)
    op.create_index(op.f('ix_contacts_organization_id'), 'contacts', ['organization_id'], unique=False)
    op.create_table('meet_and_greets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('dog_id', sa.String(), nullable=False),
    sa.Column('household_id', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conducted_by', sa.String(), nullable=True),
    sa.Column('outcome', sa.Enum('PASS', 'CONDITIONAL', 'FAIL', 'NO_SHOW', 'RESCHEDULED', name='meetandgreetoutcome'), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('boarding_eligible_granted', sa.Boolean(), nullable=True),
    sa.Column('daycare_eligible_granted', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conducted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meet_and_greets_dog_id'), 'meet_and_greets', ['dog_id'], unique=False)
    op.create_index(op.f('ix_meet_and_greets_household_id'), 'meet_and_greets', ['household_id'], unique=False)
    op.create_index(op.f('ix_meet_and_greets_organization_id'), 'meet_and_greets', ['organization_id'], unique=False)
    op.create_table('vaccination_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('dog_id', sa.String(), nullable=False),
    sa.Column('vaccination_type', sa.String(), nullable=False),
    sa.Column('administration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='vaccinationstatus'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('document_path', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccination_records_dog_id'), 'vaccination_records', ['dog_id'], unique=False)
    op.create_index(op.f('ix_vaccination_records_organization_id'), 'vaccination_records', ['organization_id'], unique=False)
    op.add_column('dogs', sa.Column('veterinarian_id', sa.String(), nullable=True))
    op.add_column('dogs', sa.Column('spay_neuter_status', sa.String(), nullable=True))
    op.add_column('dogs', sa.Column('microchip_number', sa.String(), nullable=True))
    op.add_column('dogs', sa.Column('meet_and_greet_status', sa.String(), nullable=True))
    op.add_column('dogs', sa.Column('meet_and_greet_outcome', sa.String(), nullable=True))
    op.add_column('dogs', sa.Column('boarding_eligible', sa.Boolean(), nullable=True))
    op.add_column('dogs', sa.Column('daycare_eligible', sa.Boolean(), nullable=True))
    op.add_column('dogs', sa.Column('is_deceased', sa.Boolean(), nullable=True))
    op.add_column('dogs', sa.Column('escape_risk', sa.Boolean(), nullable=True))
    op.add_column('dogs', sa.Column('medical_alert', sa.Boolean(), nullable=True))
    op.create_foreign_key('dogs_veterinarian_id_fkey', 'dogs', 'veterinarians', ['veterinarian_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dogs_veterinarian_id_fkey', 'dogs', type_='foreignkey')
    op.drop_column('dogs', 'medical_alert')
    op.drop_column('dogs', 'escape_risk')
    op.drop_column('dogs', 'is_deceased')
    op.drop_column('dogs', 'daycare_eligible')
    op.drop_column('dogs', 'boarding_eligible')
    op.drop_column('dogs', 'meet_and_greet_outcome')
    op.drop_column('dogs', 'meet_and_greet_status')
    op.drop_column('dogs', 'microchip_number')
    op.drop_column('dogs', 'spay_neuter_status')
    op.drop_column('dogs', 'veterinarian_id')
    op.drop_index(op.f('ix_vaccination_records_organization_id'), table_name='vaccination_records')
    op.drop_index(op.f('ix_vaccination_records_dog_id'), table_name='vaccination_records')
    op.drop_table('vaccination_records')
    op.drop_index(op.f('ix_meet_and_greets_organization_id'), table_name='meet_and_greets')
    op.drop_index(op.f('ix_meet_and_greets_household_id'), table_name='meet_and_greets')
    op.drop_index(op.f('ix_meet_and_greets_dog_id'), table_name='meet_and_greets')
    op.drop_table('meet_and_greets')
    op.drop_index(op.f('ix_contacts_organization_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_household_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_behavior_profiles_organization_id'), table_name='behavior_profiles')
    op.drop_index(op.f('ix_behavior_profiles_dog_id'), table_name='behavior_profiles')
    op.drop_table('behavior_profiles')
    op.drop_index(op.f('ix_households_organization_id'), table_name='households')
    op.drop_table('households')
    op.drop_index(op.f('ix_veterinarians_organization_id'), table_name='veterinarians')
    op.drop_table('veterinarians')
    # ### end Alembic commands ###
