"""add_phase4_stay_tables

Revision ID: f6cbce1a4f57
Revises: 78a60d2bbbe5
Create Date: 2026-06-08 23:58:42.392514
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6cbce1a4f57'
down_revision = '78a60d2bbbe5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stays',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('booking_id', sa.String(), nullable=False),
    sa.Column('dog_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('EXPECTED', 'ON_SITE', 'TEMPORARILY_OFF_SITE', 'CHECKED_OUT', name='staystatus'), nullable=False),
    sa.Column('room_id', sa.String(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_by', sa.String(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_out_by', sa.String(), nullable=True),
    sa.Column('is_first_stay', sa.Boolean(), nullable=True),
    sa.Column('intake_condition_note', sa.Text(), nullable=True),
    sa.Column('belongings_note', sa.Text(), nullable=True),
    sa.Column('checkout_summary', sa.Text(), nullable=True),
    sa.Column('last_handoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['checked_in_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['checked_out_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stays_booking_id'), 'stays', ['booking_id'], unique=False)
    op.create_index(op.f('ix_stays_dog_id'), 'stays', ['dog_id'], unique=False)
    op.create_index(op.f('ix_stays_organization_id'), 'stays', ['organization_id'], unique=False)
    op.create_table('checkout_pickup_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('stay_id', sa.String(), nullable=False),
    sa.Column('pickup_person_name', sa.String(), nullable=False),
    sa.Column('relationship_to_household', sa.String(), nullable=True),
    sa.Column('is_authorized_pickup', sa.Boolean(), nullable=True),
    sa.Column('id_verified', sa.Boolean(), nullable=True),
    sa.Column('id_type', sa.String(), nullable=True),
    sa.Column('confirmed_by', sa.String(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['stays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkout_pickup_records_organization_id'), 'checkout_pickup_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_checkout_pickup_records_stay_id'), 'checkout_pickup_records', ['stay_id'], unique=False)
    op.create_table('room_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('stay_id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('assigned_by', sa.String(), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason_for_move', sa.Text(), nullable=True),
    sa.Column('compatibility_override', sa.Boolean(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['stays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_assignments_organization_id'), 'room_assignments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_room_assignments_room_id'), 'room_assignments', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_assignments_stay_id'), 'room_assignments', ['stay_id'], unique=False)
    op.create_table('stay_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('stay_id', sa.String(), nullable=False),
    sa.Column('dog_id', sa.String(), nullable=False),
    sa.Column('alert_message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'CAUTION', 'WARNING', name='stayalertseverity'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleared_by', sa.String(), nullable=True),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleared_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cleared_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['stays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stay_alerts_dog_id'), 'stay_alerts', ['dog_id'], unique=False)
    op.create_index(op.f('ix_stay_alerts_organization_id'), 'stay_alerts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_stay_alerts_stay_id'), 'stay_alerts', ['stay_id'], unique=False)
    op.create_table('stay_feeding_overrides',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('stay_id', sa.String(), nullable=False),
    sa.Column('dog_id', sa.String(), nullable=False),
    sa.Column('override_type', sa.String(), nullable=False),
    sa.Column('override_detail', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['stays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stay_feeding_overrides_dog_id'), 'stay_feeding_overrides', ['dog_id'], unique=False)
    op.create_index(op.f('ix_stay_feeding_overrides_organization_id'), 'stay_feeding_overrides', ['organization_id'], unique=False)
    op.create_index(op.f('ix_stay_feeding_overrides_stay_id'), 'stay_feeding_overrides', ['stay_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stay_feeding_overrides_stay_id'), table_name='stay_feeding_overrides')
    op.drop_index(op.f('ix_stay_feeding_overrides_organization_id'), table_name='stay_feeding_overrides')
    op.drop_index(op.f('ix_stay_feeding_overrides_dog_id'), table_name='stay_feeding_overrides')
    op.drop_table('stay_feeding_overrides')
    op.drop_index(op.f('ix_stay_alerts_stay_id'), table_name='stay_alerts')
    op.drop_index(op.f('ix_stay_alerts_organization_id'), table_name='stay_alerts')
    op.drop_index(op.f('ix_stay_alerts_dog_id'), table_name='stay_alerts')
    op.drop_table('stay_alerts')
    op.drop_index(op.f('ix_room_assignments_stay_id'), table_name='room_assignments')
    op.drop_index(op.f('ix_room_assignments_room_id'), table_name='room_assignments')
    op.drop_index(op.f('ix_room_assignments_organization_id'), table_name='room_assignments')
    op.drop_table('room_assignments')
    op.drop_index(op.f('ix_checkout_pickup_records_stay_id'), table_name='checkout_pickup_records')
    op.drop_index(op.f('ix_checkout_pickup_records_organization_id'), table_name='checkout_pickup_records')
    op.drop_table('checkout_pickup_records')
    op.drop_index(op.f('ix_stays_organization_id'), table_name='stays')
    op.drop_index(op.f('ix_stays_dog_id'), table_name='stays')
    op.drop_index(op.f('ix_stays_booking_id'), table_name='stays')
    op.drop_table('stays')
    # ### end Alembic commands ###
