"""add_facility_status_table

Revision ID: ffd49af18b69
Revises: 9b6678a44a2c
Create Date: 2026-06-08 01:56:41.790495
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd49af18b69'
down_revision = '9b6678a44a2c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_status',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'HOLIDAY', 'EMERGENCY_CLOSURE', name='facilitystatustype'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('affects_bookings', sa.Boolean(), nullable=True),
    sa.Column('set_by', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['set_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_status_organization_id'), 'facility_status', ['organization_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facility_status_organization_id'), table_name='facility_status')
    op.drop_table('facility_status')
    # ### end Alembic commands ###
